services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: scourt-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:-Your_password123}"
    ports:
      - "1433:1433"
    volumes:
      - scourt-sqlserver-data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    container_name: scourt-redis
    ports:
      - "6379:6379"

volumes:
  scourt-sqlserver-data:
